### ISSUE TITLE
AssertionError when training panoptic segmentation head

### ISSUE THREAD

**Issue by DanielFennhagen** [facebookresearch/detr#232]
Hi, thanks again for the work put into this project!

I have trained a object detection model on a custom dataset and now want to train the segmentation head, however I get the following error after a few batches of training:

```
File "/home/daniel/Work/detr/util/box_ops.py", line 53, in generalized_box_iou
assert (boxes2[:, 2:] >= boxes2[:, :2]).all()
AssertionError
```

<details>
<summary>Full traceback</summary>

```
Traceback (most recent call last):
File "main.py", line 307, in <module>
main(args)
File "main.py", line 212, in main
train_stats = train_one_epoch(
File "/home/daniel/Work/detr/engine.py", line 33, in train_one_epoch
loss_dict = criterion(outputs, targets)
File "/home/daniel/.conda/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
result = self.forward(*input, **kwargs)
File "/home/daniel/Work/detr/models/detr.py", line 225, in forward
indices = self.matcher(outputs_without_aux, targets)
File "/home/daniel/.conda/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
result = self.forward(*input, **kwargs)
File "/home/daniel/.conda/envs/pytorch/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
return func(*args, **kwargs)
File "/home/daniel/Work/detr/models/matcher.py", line 74, in forward
cost_giou = -generalized_box_iou(box_cxcywh_to_xyxy(out_bbox), box_cxcywh_to_xyxy(tgt_bbox))
File "/home/daniel/Work/detr/util/box_ops.py", line 53, in generalized_box_iou
assert (boxes2[:, 2:] >= boxes2[:, :2]).all()
AssertionError
```

</details>

My dataset contains 3 classes and as such I have modified the num_classes, in argparse too. It is consistent with https://github.com/facebookresearch/detr/issues/28#issuecomment-636712413

Any idea of why I'm getting this error?

**Comment by DanielFennhagen** [comment]
Further investigation shows that following is the tensor that fails the assertion:

```
[[5.7188e-01, 3.2197e-01, 9.5625e-01, 8.0729e-01],
 [1.5625e-03, 3.2080e-01, 9.5781e-01, 9.2479e-01],
 [7.8125e+04, 1.1751e+05, 0.0000e+00, 0.0000e+00]]
```

The dataset does not contain any zero-size bounding boxes so my guess is that this is a predicted value, however that leads me nowhere in my investigation.

Thanks!

**Comment by alcinos** [comment]
Hi @DanielFennhagen 
As you can see by tracing the call, `boxes2` corresponds to the second argument of the giou function, and in your call trace it originates from the `tgt_bbox` tensors. This is definitely coming from your dataset, you need to investigate and visualize what your boxes are looking like.
I'm not sure where you are printing the failing box from, but ignoring the 0,0 values, the two first coordinates of the last box are wrong, everything should always be normalized in [0, 1]. 
Please double check that you're not doing fishy in the data augmentation or something.

Best of luck.

**Comment by DanielFennhagen** [comment]
Thanks for the response @alcinos!

The boxes was printed from boxes2 in https://github.com/facebookresearch/detr/blob/1d62eba47bc85d17ff0b5d3657a4991866de677c/util/box_ops.py#L50-L53

I have not changed any part of the data augmentation from your repo. Just to make sure, the boxes are supposed to be in xywh format, right?

After visualizing boxes on the entire dataset I could not find any obvious error with the dataset.
I will try training the panoptic head with the official coco dataset verify that the error is on my part.

I'll post an update tomorrow.

**Comment by fmassa** [comment]
If it can be of help,  note that we remove all boxes that have a size of zero, maybe you are missing something like that in your dataset?

https://github.com/facebookresearch/detr/blob/647917626d5017e63c1217b99537deb2dcb370d6/datasets/coco.py#L86-L88

**Comment by DanielFennhagen** [comment]
Thanks for the help @alcinos and @fmassa!. 
The problem was indeed that my input data was incorrect! For future reference I will explain how we found the problem and what caused it.

<details closed>
<summary>The problem and solution</summary>
<br>
As suggested by @alcinos the problem was with the `tgt_bbox` in the giou function:

https://github.com/facebookresearch/detr/blob/647917626d5017e63c1217b99537deb2dcb370d6/models/matcher.py#L74

I was very certain that my annotations were correct so after doing some edge case detection on my annotation json file I concluded that it was not the issue.

I then delved deeper into the dataset builder (since the problem did not occur with the `--dataset_file 'coco'` parameter I figured it had to do with the panoptic builder. Following this led me to `__getitem__`, and more specifically the rgb2id function:
https://github.com/facebookresearch/detr/blob/647917626d5017e63c1217b99537deb2dcb370d6/datasets/coco_panoptic.py#L43

Here is where I learned that the masks are not used from the dataset annotation json file but rather retrieved from the panoptic annotation image.

I then displayed the masks tensor as an image and it looked like the following:
![masks](https://user-images.githubusercontent.com/70580355/93994361-1654de00-fd90-11ea-8a93-7881e50d12aa.jpg)

For reference this was the panoptic annotation image:
<img src="https://user-images.githubusercontent.com/70580355/93992455-dd1b6e80-fd8d-11ea-81b4-8b65333da247.png" width="300" height="200" />


Obviously something is not correct here, and tracing the problem did not take long.
My annotation images had been saved as .jpg files and image compression had blurred colors in the image.
I then re-generated my annotation images without using compression and displayed the new masks tensor:
![fixed_masks](https://user-images.githubusercontent.com/70580355/93994303-050bd180-fd90-11ea-88e9-933be8ba347c.jpg)

</details>

With this problem soved I am now able to train both the object detection and panoptic segmentation head. However I run into another issue after this which may or not be related.

During the test phase I get a the following RuntimeError:
`RuntimeError: Non-empty 4D data tensor expected but got a tensor with sizes [1, 0, 200, 267]`


<details closed>
<summary>Full Traceback</summary>
<br>

```

Traceback (most recent call last):
  File "/home/daniel/.conda/envs/pytorch/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/daniel/.conda/envs/pytorch/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/daniel/.vscode/extensions/ms-python.python-2020.8.109390/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/daniel/.vscode/extensions/ms-python.python-2020.8.109390/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/daniel/.vscode/extensions/ms-python.python-2020.8.109390/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/home/daniel/.conda/envs/pytorch/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/daniel/.conda/envs/pytorch/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/daniel/.conda/envs/pytorch/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/daniel/Work/detr/main.py", line 319, in <module>
    main(args)
  File "/home/daniel/Work/detr/main.py", line 230, in main
    test_stats, coco_evaluator = evaluate(
  File "/home/daniel/.conda/envs/pytorch/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/daniel/Work/detr/engine.py", line 117, in evaluate
    res_pano = postprocessors["panoptic"](outputs, target_sizes, orig_target_sizes)
  File "/home/daniel/.conda/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/daniel/Work/detr/models/segmentation.py", line 287, in forward
    cur_masks = interpolate(cur_masks[None], to_tuple(size), mode="bilinear").squeeze(0)
  File "/home/daniel/Work/detr/util/misc.py", line 467, in interpolate
    return torchvision.ops.misc.interpolate(input, size, scale_factor, mode, align_corners)
  File "/home/daniel/.conda/envs/pytorch/lib/python3.8/site-packages/torch/nn/functional.py", line 3163, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, sfl[0], sfl[1])
RuntimeError: Non-empty 4D data tensor expected but got a tensor with sizes [1, 0, 200, 267]
```

</details>

It originates from:
https://github.com/facebookresearch/detr/blob/647917626d5017e63c1217b99537deb2dcb370d6/models/segmentation.py#L287
where my keep boxes are all `False`, lowering the `self.threshold` would fix this problem but I don't think that is a good solution.
Any idea of where to start with this problem?

**Comment by fmassa** [comment]
@DanielFennhagen thanks for the report, this last error you are facing is a bug in our code I believe.
You should replace
```python
cur_masks = interpolate(cur_masks[None], to_tuple(size), mode="bilinear").squeeze(0)
```
with
```python
cur_masks = interpolate(cur_masks[:, None], to_tuple(size), mode="bilinear").squeeze(1)
```
Can you try this out, and if it works send a PR fixing it?

**Comment by DanielFennhagen** [comment]
Thank you @fmassa, changing the line to 

```
cur_masks = interpolate(cur_masks[:, None], to_tuple(size), mode="bilinear").squeeze(1)
``` 
did indeed let me continue training, at least untill the end of one epoch. (Once I can train without breaking I will send a PR.)
Though this exposes another problem, at the end of the testing phase I get a ZeroDivisionError:

<details closed>
<summary>Full traceback</summary>
<br>

```
Traceback (most recent call last):
  File "main.py", line 319, in <module>
    main(args)
  File "main.py", line 230, in main
    test_stats, coco_evaluator = evaluate(
  File "/home/daniel/.conda/envs/pytorch/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/daniel/Work/detr/engine.py", line 140, in evaluate
    panoptic_res = panoptic_evaluator.summarize()
  File "/home/daniel/Work/detr/datasets/panoptic_eval.py", line 43, in summarize
    return pq_compute(self.gt_json, predictions_json, gt_folder=self.gt_folder, pred_folder=self.output_dir)
  File "/home/daniel/.conda/envs/pytorch/lib/python3.8/site-packages/panopticapi/evaluation.py", line 223, in pq_compute
    results[name], per_class_results = pq_stat.pq_average(categories, isthing=isthing)
  File "/home/daniel/.conda/envs/pytorch/lib/python3.8/site-packages/panopticapi/evaluation.py", line 72, in pq_average
    return {'pq': pq / n, 'sq': sq / n, 'rq': rq / n, 'n': n}, per_class_results
ZeroDivisionError: division by zero
```

</details>

This can be avoided by adding the following line:
```
if isthing != cat_isthing:
    n=1
    continue
```
in `panopticapi.evaluation.py`, called from:
https://github.com/facebookresearch/detr/blob/647917626d5017e63c1217b99537deb2dcb370d6/datasets/panoptic_eval.py#L43

However I do not know how this will effect the results of training. Though from what I can see this only changes the logged values of the training.
Do you know of a better way to solve this?

**Comment by DanielFennhagen** [comment]
The previous error was caused by me, the `isthing` had been stored as a string.

I can now train the panoptic head.
Thank you very much for the help @alcinos & @fmassa!

**Comment by fmassa** [comment]
Fixed by https://github.com/facebookresearch/detr/pull/244

**Comment by Dicko87** [comment]
Hi @fmassa, @DanielFennhagen, I am also getting exactly the same ZeroDivisionError and was curious how did you solve this? I made the change outlined above #244 but still getting the error (probably unrelated to the fix). I checked the isthing value and type by using print statements, in my json files my isthing has the value of 1 as an integer for my custom datatset. 

![image](https://user-images.githubusercontent.com/37139958/137756559-524e7df1-11f7-4b2b-aee2-56d0edac2165.png)
