### ISSUE TITLE
interpolating empty tensors is not supported

### ISSUE THREAD

**Issue by Jacobew** [facebookresearch/detr#263]
Hi, I found that the interpolate function [here](https://github.com/facebookresearch/detr/blob/4e1a9281bc5621dcd65f3438631de25e255c4269/util/misc.py#L450) does not support interpolating empty tensors. 
As a result, I got the following error in segmentation.py:

> RuntimeError: Non-empty 4D data tensor expected but got a tensor with sizes [1, 0, 267, 267]

Minimal script to reproduce the error:
```
import torch
import torchvision
if float(torchvision.__version__[:3]) < 0.7:
    from torchvision.ops import _new_empty_tensor
    from torchvision.ops.misc import _output_size
def interpolate(input, size=None, scale_factor=None, mode="nearest", align_corners=None):
    # type: (Tensor, Optional[List[int]], Optional[float], str, Optional[bool]) -> Tensor
    """
    Equivalent to nn.functional.interpolate, but with support for empty batch sizes.
    This will eventually be supported natively by PyTorch, and this
    class can go away.
    """
    if float(torchvision.__version__[:3]) < 0.7:
        if input.numel() > 0:
            return torch.nn.functional.interpolate(
                input, size, scale_factor, mode, align_corners
            )
        output_shape = _output_size(2, input, size, scale_factor)
        output_shape = list(input.shape[:-2]) + list(output_shape)
        return _new_empty_tensor(input, output_shape)
    else:
        return torchvision.ops.misc.interpolate(input, size, scale_factor, mode, align_corners)

a = torch.Tensor(1, 0, 267, 267)
print(interpolate(a, (300, 300), mode="bilinear").shape)
```
With torchvision < 0.7.0, this function works well but it does not with torchvision 0.7.0. 
Any idea to fix it under torchvision 0.7.0?

**Comment by Jacobew** [comment]
@alcinos @fmassa

**Comment by Jacobew** [comment]
If I downgrade to torchvision0.6.0, this error in evaluation gone away, but I got another error in training.

```
Original Traceback (most recent call last):
  File "/home/anaconda3/envs/detr-pan/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/anaconda3/envs/detr-pan/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/anaconda3/envs/detr-pan/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/detr-pan/detr-panoptic/datasets/coco_panoptic.py", line 66, in __getitem__
    img, target = self.transforms(img, target)
  File "/home/detr-pan/detr-panoptic/datasets/transforms.py", line 268, in __call__
    image, target = t(image, target)
  File "/home/detr-pan/detr-panoptic/datasets/transforms.py", line 226, in __call__
    return self.transforms2(img, target)
  File "/home/detr-pan/detr-panoptic/datasets/transforms.py", line 268, in __call__
    image, target = t(image, target)
  File "/home/detr-pan/detr-panoptic/datasets/transforms.py", line 200, in __call__
    return resize(img, target, size, self.max_size)
  File "/home/detr-pan/detr-panoptic/datasets/transforms.py", line 130, in resize
    target['masks'] = interpolate(
  File "/home/detr-pan/detr-panoptic/util/misc.py", line 426, in interpolate
    output_shape = _output_size(2, input, size, scale_factor)
  File "/home/anaconda3/envs/detr-pan/lib/python3.8/site-packages/torchvision/ops/misc.py", line 90, in _output_size
    _check_size_scale_factor(dim, size, scale_factor)
  File "/home/anaconda3/envs/detr-pan/lib/python3.8/site-packages/torchvision/ops/misc.py", line 83, in _check_size_scale_factor
    "Input is {}D, scale_factor size is {}".format(dim, len(scale_factor))
TypeError: object of type 'NoneType' has no len()
```
Seems that this is caused by not providing scale_factor to the _output_size function.

Can I just replace the these lines 
```
output_shape = _output_size(2, input, size, scale_factor)
output_shape = list(input.shape[:-2]) + list(output_shape)
return _new_empty_tensor(input, output_shape)
```

by 

```
output_shape = list(input.shape[:-2]) + list(size)
return _new_empty_tensor(input, output_shape)
```
? I wonder if this is a proper correction.

**Comment by Jacobew** [comment]
After I applied the modification above and used torchvision 0.6.0,  I managed to run through the panoptic segmentation training process, but the results are weird. 

1. I extracted the submodel in this [checkpoint (43.4 PQ)](https://dl.fbaipublicfiles.com/detr/detr-r50-panoptic-00ce5173.pth) and trained the panoptic model following the instructions.  
I did get a similar box/segm ap with the reported ones, but PQ is quite low. 
This is the PQ curve in training:
![image](https://user-images.githubusercontent.com/26053586/97111851-09733380-171c-11eb-873e-c6dafa8b24e3.png)
The final PQ is 25.0 which is much lower than the reported one(43.4). 

Any ideas?

**Comment by Jacobew** [comment]
@alcinos @fmassa

**Comment by fmassa** [comment]
For the first question, this is an issue with DETR codebase which was fixed in https://github.com/facebookresearch/detr/pull/244

For the second question, I've recently trained a panoptic model in https://github.com/facebookresearch/detr/issues/247#issuecomment-701598742 and got good accuracies, so I'm not sure what the issue could be.

**Comment by Jacobew** [comment]
@fmassa  Thanks for your reply! 
Regarding the second question, I've double-checked the results I got but the problem still exists (even on a new machine). 
I use the latest code and the only modification is that I change [this line](https://github.com/facebookresearch/detr/blob/4e1a9281bc5621dcd65f3438631de25e255c4269/main.py#L169) to 
```
model_without_ddp.load_state_dict(checkpoint['model'])
```
The evaluation command I used:
```
python -m torch.distributed.launch --nproc_per_node=8 --use_env main.py --masks --eval \
--coco_path ../../coco --coco_panoptic_path ../coco_panoptic --dataset_file coco_panoptic \
--frozen_weights ./detr-r50-panoptic-00ce5173.pth --output_dir ./panoptic_model
```

Could you please evaluate `detr-r50-panoptic-00ce5173.pth` with this command and see if you can reproduce the results in paper?

**Comment by GengDavid** [comment]
Hi, @fmassa
I also meet the same problem when evaluating panoptic segmentation model. 
I run panoptic segmentation evaluation with this command directly (using the most recently detr codes without modification):
```
 python main.py --batch_size 2 --no_aux_loss --masks --eval --resume detr-r50-panoptic-00ce5173.pth --coco_path data/coco --coco_panoptic_path data/coco/panoptic_anno --dataset_file coco_panoptic
```
I got similar PQ results (24.7% PQ) as @Jacobew. Maybe there's something wrong with the post-processing of panoptic segmentation part.

**Comment by Jacobew** [comment]
Hi, @fmassa ,  I'm just wondering if there are any updates here? I still cannot locate the issue in the evaluation of your panoptic model.

**Comment by alcinos** [comment]
The panoptic models were trained with batch_size=1, thus they need to be tested with bs=1.
The reason is that bs>1 introduce some extra padding in case images in the batch don't have the same aspect ratio, and it turns out that in the current implementation, DETR is not robust to this change if it hasn't seen it during training.
Hope this helps.
